### ISSUE TITLE
Connect not defined in gulpfile

### ISSUE THREAD

**Issue by AquilaSagitta** [reflexdemon/slush-angular-gulp#2]
ReferenceError: connect is not defined
    at Gulp.<anonymous> (C:\Users\Jenkins\Documents\Repositories\sandbox\gulpTest\gulpfile.js:169:5)
    at module.exports (C:\Users\Jenkins\Documents\Repositories\sandbox\gulpTest\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\Jenkins\Documents\Repositories\sandbox\gulpTest\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\Jenkins\Documents\Repositories\sandbox\gulpTest\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Users\Jenkins\Documents\Repositories\sandbox\gulpTest\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at C:\Users\Jenkins\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at process._tickCallback (node.js:355:11)

Had many issues trying to get generator to install without errors. Had to install gulp and python. Then gyp was having errors and had to install visual studio 2013. Now that the build is working without errors I tried launching the generated project with <code>gulp serve</code> and it gave this error. I'm new to gulp pls help!

**Comment by reflexdemon** [comment]
Thanks for letting us know about this issue. We will soon be pushing the fix. Meanwhile please do the below for quick fix.

```bash
npm i --save gulp-connect
```
Please add the below line to the `gulpfile.js` around line# 13/14.
 
```javascript

connect = require('gulp-connect'),

```

Please let us know if the issue got resolved.

**Comment by AquilaSagitta** [comment]
Yup that fixed it. Thanks for the quick response!
